name: Bug report
description: Report a bug or unexpected behaviour in IconSwapperGui
title: "[BUG] "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us investigate the issue effectively.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behaviour.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Perform '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or recordings to help explain the problem.

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Windows 10 / Windows 11
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: IconSwapperGui Version
      placeholder: e.g. v1.2.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, logs, or details that may help.
